---
- name: install.yml | Installing NGINX
  apt:
    name: nginx
    update_cache: true
    autoremove: true
    autoclean: true
    install-recommends: false
    policy_rc_d: "101"
    state: present
